### ISSUE TITLE
NPM Err! Cannot read properties of undefined (reading 'spec')

### ISSUE THREAD

**Issue by jamsandwiches** [codediodeio/sveltefire#149]
After cloning this repo, making the adjustments that the readme states, I receive the above error when npm/npx sveltefire firebase.

Received Log:
`0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\****\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.2.5
2 info using node@v20.10.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\***\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\***\Desktop\sveltefire-master\.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:C:\Users\***\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\***\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 14ms
17 timing npm:load:configload Completed in 14ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm exec i sveltefire firebase
22 verbose argv "exec" "--" "i" "sveltefire" "firebase"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:C:\Users\***\AppData\Local\npm-cache\_logs\2024-01-17T15_32_14_924Z-
26 verbose logfile C:\Users\***\AppData\Local\npm-cache\_logs\2024-01-17T15_32_14_924Z-debug-0.log
27 timing npm:load:logFile Completed in 9ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 77ms
31 silly logfile start cleaning logs, removing 2 files
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 1ms
34 http fetch GET 200 https://registry.npmjs.org/i 152ms (cache miss)
35 timing command:exec Completed in 603ms
36 verbose stack Error: could not determine executable to run
36 verbose stack     at getBinFromManifest (C:\Users\***\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
36 verbose stack     at exec (C:\Users\***\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:188:15)
36 verbose stack     at async module.exports (C:\Users\***\AppData\Roaming\npm\node_modules\npm\lib\cli-entry.js:61:5)
37 verbose pkgid i@0.3.7
38 verbose cwd C:\Users\***\Desktop\sveltefire-master
39 verbose Windows_NT 10.0.19044
40 verbose node v20.10.0
41 verbose npm  v10.2.5
42 error could not determine executable to run
43 verbose exit 1
44 timing npm Completed in 1013ms
45 verbose code 1
46 error A complete log of this run can be found in: C:\Users\***\AppData\Local\npm-cache\_logs\2024-01-17T15_32_14_924Z-debug-0.log
`

**Comment by sacrosanctic** [comment]
dont clone the repo run `npm i sveltefire`
